name: Build Aseprite on Windows

on: [push, pull_request]

jobs:
  build-windows:
    runs-on: windows-2022

    steps:
    # 1. 检出代码及子模块
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    # 2. 安装构建工具
    - name: Install build tools
      run: |
        choco install cmake ninja -y
        choco install 7zip -y

    # 3. 设置MSVC开发环境
    - name: Setup MSVC environment
      uses: ilammy/msvc-dev-cmd@v1

    # 4. 下载Skia
    - name: Download Skia
      shell: bash
      run: |
        SKIA_URL="https://github.com/aseprite/skia/releases/download/m124-08a5439a6b/Skia-Windows-Release-x64.zip"
        SKIA_ZIP="skia.zip"
        curl -L -o "$SKIA_ZIP" "$SKIA_URL"

    # 5. 解压Skia
    - name: Extract Skia
      shell: bash
      run: |
        7z x skia.zip -oskia -y
        echo "Skia 解压完成"

    # 6. 验证头文件位置（可选，用于确认）
    - name: Verify header files location
      shell: bash
      run: |
        echo "验证 libjpeg-turbo 头文件位置..."
        LIBJPEG_DIR="skia/third_party/externals/libjpeg-turbo"
        
        if [ -d "$LIBJPEG_DIR/src" ]; then
          echo "找到 src 目录，包含以下头文件:"
          ls -la "$LIBJPEG_DIR/src/" | grep "\.h$"
          echo "✓ 头文件位置确认正确"
        else
          echo "错误: 没有找到 src 目录"
          exit 1
        fi

    # 7. 创建构建目录并配置CMake（关键修改！）
    - name: Configure CMake
      shell: bash
      run: |
        mkdir -p build
        cd build
        
        cmake -G Ninja .. \
          -DCMAKE_BUILD_TYPE=Release \
          -DLAF_BACKEND=skia \
          -DSKIA_DIR=../skia \
          -DSKIA_LIBRARY_DIR=../skia/out/Release-x64 \
          -DSKIA_LIBRARY=../skia/out/Release-x64/skia.lib \
          -DLIBJPEG_TURBO_INCLUDE_DIR=../skia/third_party/externals/libjpeg-turbo/src

    # 8. 编译Aseprite
    - name: Build Aseprite
      shell: bash
      run: |
        cd build
        ninja aseprite

    # 9. 上传构建成果
    - name: Upload Aseprite Artifact
      uses: actions/upload-artifact@v4
      with:
        name: aseprite-windows-build
        path: build/bin/aseprite.exe
